### ISSUE TITLE
Up and running

### ISSUE THREAD

**Issue by kalouo** [bakingbacon/bakinbacon#3]
Hello. I'm a Tezos community member interested in your project and wondering if/how I can help. 

I downloaded the source code and tried to run `./bakinbacon -debug -trace -webuiaddr 127.0.0.1 -webuiport 8082` from both inside and outside the project root, and I get an error message along the lines of `./bakinbacon: command not found`. 

What am I missing? Would you be able to flesh out the setup instructions? 

Keen to test it and perhaps help on the React side of things... 

Thanks.

**Comment by utdrmac** [comment]
@kalouo You must first build the binary before executing. You need to have a development environment for golang and nodejs. If you don't want to do that, check the 'Releases' tab and download a precompiled version for linux.
