### ISSUE TITLE
failed to forge reveal: failed to forge public_key: invalid public key 

### ISSUE THREAD

**Issue by reskue95** [bakingbacon/bakinbacon#6]
**Describe the bug**
failing to register address as baker via ledger device.

**To Reproduce**
click register 
get error (Cannot register baker: Unable to register baker: failed to forge reveal: failed to forge public_key: invalid public key 
**Expected behavior**)

I have the correct amount of xtz needed and ledger in baker app.
expected to create baker.

**Desktop 
 - OS: Mac osx
 - Browser safari
 - Version v6

sorry if this isn't the correct way to make contact regarding this issue but I can't find any alternatives.

**Comment by utdrmac** [comment]
You successfully completed the registration steps and got a key from the device?

**Comment by reskue95** [comment]
Correct

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by utdrmac** [comment]
And then you received the funds and it said you need to register as a baker? And when you clicked on register, you got this error?

Can you try restarting BB, refresh UI, and do the baker register again? I think I know what is causing the issue if restarting BB fixes the problem.

**Comment by reskue95** [comment]
My ledger is now linked with that address and I can't fund a way to disconnect it so whenever I restart bb it just shows the same page as in the image

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by reskue95** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by utdrmac** [comment]
Can't see any images. What does the console output say when you start BB? Probably just need the first 50 lines.

**Comment by reskue95** [comment]
in-amd64 ; exit;
INFO[2021-09-09T17:37:52+01:00] === BakinBacon v1.0 (4486ec) ===             
INFO[2021-09-09T17:37:52+01:00] === Network: granadanet ===                  
INFO[2021-09-09T17:37:52+01:00] Checking version...                          
INFO[2021-09-09T17:37:54+01:00] Connected to RPC                              Endpoint="http://granadanet-us.rpc.bakinbacon.io"
INFO[2021-09-09T17:37:54+01:00] Blockwatch running...                         Endpoint="http://granadanet-us.rpc.bakinbacon.io"
WARN[2021-09-09T17:37:54+01:00] Switched active RPC                           Endpoint="http://granadanet-us.rpc.bakinbacon.io"
INFO[2021-09-09T17:37:54+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BLCqfNUG2C7wKtYCEmczhqdPgEcMZPGawXh99cfGXGVi8r8rotX Level=439406
INFO[2021-09-09T17:37:56+01:00] Connected to RPC                              Endpoint="http://granadanet-eu.rpc.bakinbacon.io"
INFO[2021-09-09T17:37:56+01:00] Blockwatch running...                         Endpoint="http://granadanet-eu.rpc.bakinbacon.io"
INFO[2021-09-09T17:37:58+01:00] Bakin'Bacon WebUI Listening                   Addr="127.0.0.1:8082"
INFO[2021-09-09T17:37:58+01:00] Loaded delegate public key hash from DB       Delegate=tz1dTDGGnXepEsb7BTE7NEb6mViNRU1suzwX
ERRO[2021-09-09T17:37:59+01:00] Checking baker registration                   error="Delegate not registered"
ERRO[2021-09-09T17:38:00+01:00] Checking baker registration                   error="Delegate not registered"
INFO[2021-09-09T17:38:02+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BM1Rs3azU5i15xec3P1RQCGjt8yNraoJC829Vaq5mQfyKYFjGRY Level=439407
ERRO[2021-09-09T17:38:03+01:00] Checking baker registration                   error="Delegate not registered"
./bakinbacon-linux-amd64 [-debug] [-trace] [-webuiaddr 127.0.0.1] [-webuiport 8082] [-network mainnet|granadanet]

INFO[2021-09-09T17:38:15+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BL5yXdUHrEyc9PcRKLt7wJFWqsV5XjLcjYjLdCS28ZRbWzvca3u Level=439408
ERRO[2021-09-09T17:38:16+01:00] Checking baker registration                   error="Delegate not registered"
INFO[2021-09-09T17:38:25+01:00] Baker address is not revealed                
INFO[2021-09-09T17:38:27+01:00] Baker address is not revealed                
INFO[2021-09-09T17:38:29+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BKvyFY8WUN5C8oXdZ3qoLuifigNNhRSsEeyTsqTRZm2JnLdo1HT Level=439409
ERRO[2021-09-09T17:38:30+01:00] Checking baker registration                   error="Delegate not registered"
INFO[2021-09-09T17:38:51+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BLA2FdN3z8aXi7qssVMp7X3SLHcpw47FqG2bHpN4xbyRGwkD6jc Level=439410
ERRO[2021-09-09T17:38:52+01:00] Checking baker registration                   error="Delegate not registered"
INFO[2021-09-09T17:39:32+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BLGnLHK9wAxkBH85UDcDEgXNpUGgr6DA8AZemdiV8KzLeG4XPY5 Level=439411
ERRO[2021-09-09T17:39:33+01:00] Checking baker registration                   error="Delegate not registered"
INFO[2021-09-09T17:39:54+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BL36ACXYAB54EK3Gf5kozbKXWbZDepB7BXU7gJ5cFhFo1kQHjiD Level=439412
ERRO[2021-09-09T17:39:54+01:00] Checking baker registration                   error="Delegate not registered"
INFO[2021-09-09T17:40:08+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BMGDuxYGjvEEpaASu5iT9yRCKc8UFhDoFEKXZbyjsFFBH4u6cA1 Level=439413
ERRO[2021-09-09T17:40:09+01:00] Checking baker registration                   error="Delegate not registered"
WARN[2021-09-09T17:40:16+01:00] Switched active RPC                           Endpoint="http://granadanet-eu.rpc.bakinbacon.io"
INFO[2021-09-09T17:40:16+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BLnDyPMeqcxXFQQcHL3h9uN1Azv4Qh2AVtbF8WQKLRAEFyVp7qv Level=439414
ERRO[2021-09-09T17:40:17+01:00] Checking baker registration                   error="Delegate not registered"
WARN[2021-09-09T17:40:35+01:00] Switched active RPC                           Endpoint="http://granadanet-us.rpc.bakinbacon.io"
INFO[2021-09-09T17:40:35+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BLXF3taVTf2GsooEg8SvMXXwDu17537tEL9H693SiB55ZqC2LUm Level=439415
ERRO[2021-09-09T17:40:35+01:00] Checking baker registration                   error="Delegate not registered"
INFO[2021-09-09T17:40:50+01:00] New Block                                     ChainID=NetXz969SFaFn8k Cycle=108 Hash=BKnGy6TroZwK53gLGnTB6w4mVMDuCEwWijiVbGimBKLQuSYj9mY Level=439416
ERRO[2021-09-09T17:40:51+01:00] Checking baker registration                   error="Delegate not registered"

**Comment by utdrmac** [comment]
Ok. You need to start BB with -debug. Did you literally copy the `[ ]` symbols? You shouldn't have done that. Those are standard indicators that parameters within the [ ] are optional. Please restart BB like this:

`./bakinbacon-linux-amd64 -debug -trace -network granadanet`

Then, reload the UI and attempt to register again. Send those logs.

**Comment by reskue95** [comment]
ok I have done this how can I send you the logs without the []?
problem still persists.

**Comment by utdrmac** [comment]
You need to run bb as I showed in the previous post and post the logs as you did before.

**Comment by reskue95** [comment]
[36mINFO[0m[2021-09-09T19:35:28+01:00] === BakinBacon v1.0 (4486ec) ===             
[36mINFO[0m[2021-09-09T19:35:28+01:00] === Network: granadanet ===                  
[37mDEBU[0m[2021-09-09T19:35:28+01:00] Loaded Network Constants                      [37mBlocksPerCommitment[0m=32 [37mBlocksPerCycle[0m=4096 [37mTimeBetweenBlocks[0m=15
[31mERRO[0m[2021-09-09T19:35:28+01:00] No signer type defined. New setup?            [31mType[0m=0
[36mINFO[0m[2021-09-09T19:35:28+01:00] Checking version...                          
[36mINFO[0m[2021-09-09T19:35:29+01:00] Connected to RPC                              [36mEndpoint[0m="http://granadanet-us.rpc.bakinbacon.io"
[36mINFO[0m[2021-09-09T19:35:29+01:00] Blockwatch running...                         [36mEndpoint[0m="http://granadanet-us.rpc.bakinbacon.io"
[33mWARN[0m[2021-09-09T19:35:29+01:00] Switched active RPC                           [33mEndpoint[0m="http://granadanet-us.rpc.bakinbacon.io"
[36mINFO[0m[2021-09-09T19:35:29+01:00] New Block                                     [36mChainID[0m=NetXz969SFaFn8k [36mCycle[0m=108 [36mHash[0m=BL8wqg9bnqe3nh4EncdqHDALyT1skTRx1isNmURv4z7e2ZPcsfb [36mLevel[0m=439854
[36mINFO[0m[2021-09-09T19:35:31+01:00] Connected to RPC                              [36mEndpoint[0m="http://granadanet-eu.rpc.bakinbacon.io"
[36mINFO[0m[2021-09-09T19:35:31+01:00] Blockwatch running...                         [36mEndpoint[0m="http://granadanet-eu.rpc.bakinbacon.io"
[36mINFO[0m[2021-09-09T19:35:33+01:00] Bakin'Bacon WebUI Listening                   [36mAddr[0m="127.0.0.1:8082"
[36mINFO[0m[2021-09-09T19:35:33+01:00] Sent Telegram Message                         [36mMSG[0m="Loading Delegate: No delegate key defined"
[31mERRO[0m[2021-09-09T19:35:33+01:00] Checking signer status                        [31merror[0m="Loading Delegate: No delegate key defined"
[36mINFO[0m[2021-09-09T19:35:33+01:00] Notification last sent within 10 minutes     
[31mERRO[0m[2021-09-09T19:35:33+01:00] Checking signer status                        [31merror[0m="Loading Delegate: No delegate key defined"
[37mDEBU[0m[2021-09-09T19:35:36+01:00] tick...                                       [37mId[0m=1
[37mDEBU[0m[2021-09-09T19:35:38+01:00] tick...                                       [37mId[0m=2
[37mDEBU[0m[2021-09-09T19:35:43+01:00] tick...                                       [37mId[0m=1
[36mINFO[0m[2021-09-09T19:35:43+01:00] New Block                                     [36mChainID[0m=NetXz969SFaFn8k [36mCycle[0m=108 [36mHash[0m=BLWzuZNuKMh9e7hjfuxcW6iHtEzHsMZg6ZFmc9bCKKypx1zcWhB [36mLevel[0m=439855
[36mINFO[0m[2021-09-09T19:35:43+01:00] Notification last sent within 10 minutes     
[31mERRO[0m[2021-09-09T19:35:43+01:00] Checking signer status                        [31merror[0m="Loading Delegate: No delegate key defined"
[37mDEBU[0m[2021-09-09T19:35:45+01:00] tick...                                       [37mId[0m=2
[37mDEBU[0m[2021-09-09T19:35:46+01:00] API - GetStatus                              
[37mDEBU[0m[2021-09-09T19:35:50+01:00] tick...                                       [37mId[0m=1
[37mDEBU[0m[2021-09-09T19:35:52+01:00] tick...                                       [37mId[0m=2
[37mDEBU[0m[2021-09-09T19:35:56+01:00] API - testLedger                             
[37mDEBU[0m[2021-09-09T19:35:56+01:00] HID Device                                    [37mManuf[0m=Ledger [37mPath[0m="IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT2@14200000/Nano S@14200000/Nano S@0/AppleUserUSBHostHIDDevice" [37mProductID[0m=1 [37mProductName[0m="Nano S" [37mVendorID[0m=11415
[36mINFO[0m[2021-09-09T19:35:56+01:00] Ledger Version                                [36mVersion[0m="Baking 2.2.11"
[36mINFO[0m[2021-09-09T19:35:56+01:00] Ledger previously configured for baking       [36mPath[0m="/44'/1729'/0'/1'"
[37mDEBU[0m[2021-09-09T19:35:56+01:00] API - GetStatus                              
[37mDEBU[0m[2021-09-09T19:35:57+01:00] tick...                                       [37mId[0m=1
[36mINFO[0m[2021-09-09T19:35:57+01:00] New Block                                     [36mChainID[0m=NetXz969SFaFn8k [36mCycle[0m=108 [36mHash[0m=BLMwsSfcxcsuii8pte8wdmvXXuRfKoxUQsY9MRQbwiurEMsGWuK [36mLevel[0m=439856
[36mINFO[0m[2021-09-09T19:35:57+01:00] Notification last sent within 10 minutes     
[31mERRO[0m[2021-09-09T19:35:57+01:00] Checking signer status                        [31merror[0m="Loading Delegate: No delegate key defined"
[37mDEBU[0m[2021-09-09T19:35:59+01:00] tick...                                       [37mId[0m=2
[37mDEBU[0m[2021-09-09T19:36:03+01:00] API - confirmBakingPkh                       
[37mDEBU[0m[2021-09-09T19:36:03+01:00] Confirming Baking PKH                         [37mPKH[0m=tz1dTDGGnXepEsb7BTE7NEb6mViNRU1suzwX [37mPath[0m="/44'/1729'/0'/1'"
[37mDEBU[0m[2021-09-09T19:36:04+01:00] tick...                                       [37mId[0m=1
[37mDEBU[0m[2021-09-09T19:36:06+01:00] API - GetStatus                              
[37mDEBU[0m[2021-09-09T19:36:06+01:00] tick...                                       [37mId[0m=2
[33mWARN[0m[2021-09-09T19:36:06+01:00] Switched active RPC                           [33mEndpoint[0m="http://granadanet-eu.rpc.bakinbacon.io"
[36mINFO[0m[2021-09-09T19:36:06+01:00] Notification last sent within 10 minutes     
[36mINFO[0m[2021-09-09T19:36:06+01:00] New Block                                     [36mChainID[0m=NetXz969SFaFn8k [36mCycle[0m=108 [36mHash[0m=BMcmBzp16MER7ewgD8nmTsocU3SMU8oTdr56h3U6Jg6U1XCwAAs [36mLevel[0m=439857
[31mERRO[0m[2021-09-09T19:36:06+01:00] Checking signer status                        [31merror[0m="Loading Delegate: No delegate key defined"
[37mDEBU[0m[2021-09-09T19:36:11+01:00] tick...                                       [37mId[0m=1
[36mINFO[0m[2021-09-09T19:36:12+01:00] Saved authorized baking on ledger             [36mBakerPKH[0m=tz1dTDGGnXepEsb7BTE7NEb6mViNRU1suzwX [36mBipPath[0m="/44'/1729'/0'/1'"
[36mINFO[0m[2021-09-09T19:36:12+01:00] Loaded delegate public key hash from DB       [36mDelegate[0m=tz1dTDGGnXepEsb7BTE7NEb6mViNRU1suzwX
[37mTRAC[0m[2021-09-09T19:36:12+01:00] Fetching delegate info                        [37mRequest[0m="http://granadanet-eu.rpc.bakinbacon.io/chains/main/blocks/BMcmBzp16MER7ewgD8nmTsocU3SMU8oTdr56h3U6Jg6U1XCwAAs/context/contracts/tz1dTDGGnXepEsb7BTE7NEb6mViNRU1suzwX" [37mResponse[0m="{\"balance\":\"8010000000\",\"counter\":\"483098\"}\n"
[31mERRO[0m[2021-09-09T19:36:12+01:00] Checking baker registration                   [31merror[0m="Delegate not registered"
[37mDEBU[0m[2021-09-09T19:36:13+01:00] tick...                                       [37mId[0m=2
[37mDEBU[0m[2021-09-09T19:36:16+01:00] API - GetStatus                              
[37mDEBU[0m[2021-09-09T19:36:18+01:00] tick...

**Comment by reskue95** [comment]
[log-bakinbacon-2021-09-09.log](https://github.com/bakingbacon/bakinbacon/files/7139087/log-bakinbacon-2021-09-09.log)

**Comment by utdrmac** [comment]
There's nothing new in that log. I need to see the events that happen up to and after you click to register baker.

**Comment by reskue95** [comment]
[log-bakinbacon-2021-09-09.log](https://github.com/bakingbacon/bakinbacon/files/7139152/log-bakinbacon-2021-09-09.log)

**Comment by utdrmac** [comment]
Look, I really need your help here. I need you to read these logs before sending them because you're not sending me what I keep asking for. Please start BB in a fresh console, load the UI, attempt to register the baker. You will see all of these steps in the logs. I need to see the ERRO messages which happen after you click register baker.

**Comment by utdrmac** [comment]
You should see a DEBU line that says "API - registerbaker" when you attempt this action.

**Comment by utdrmac** [comment]
Yes, but I don't see any further errors that you are talking about in the logs. The message 'Baker address is not revealed' appears during the RegisterBaker function which is executed when you click the button in the UI. The next steps that BB does is to forge the reveal, forge the registration, and then prompts the ledger to sign the operations. There should be tons of error messages in the logs if any of those steps fails and I don't see any errors in your logs.

**Comment by reskue95** [comment]
ok nothing is coming up in the log after those lines I just sent.

I am receiving on the ui. Cannot register baker: Unable to register baker: failed to forge reveal: failed to forge public_key: invalid public key 'tz1dTDGGnXepEsb7BTE7NEb6mViNRU1suzwX' 

nothing comes up on the ledger either.

**Comment by utdrmac** [comment]
Ok. I think I found the issue. Give me several hours to fix. I'll push a new mac binary for you to try out.

**Comment by utdrmac** [comment]
Give this a try. [bakinbacon-darwin-amd64.tar.gz](https://github.com/bakingbacon/bakinbacon/files/7139831/bakinbacon-darwin-amd64.tar.gz)

**Comment by reskue95** [comment]
that solved the issue, thank you for the help

**Comment by utdrmac** [comment]
@reskue95 Awesome! Thanks for helping. Can you also do one more thing? You're on MacOS and don't seem to have any issues. Myself and one other can't get our ledgers working anymore. LedgerLive won't even recognize mine. Can you tell me what versions of the following you are running: macOS, ledger firmware (Secure Element, and Microcontroller versions), tezos baker app

**Comment by reskue95** [comment]
MacOs: 10.15.7
Ledger firmware: 2.0
Secure element: 2.0.0
Microcontroller 1.12
Tezos baker app: 2.2.11

I have since had problems delegating to the baker. am I missing something?
[log-bakinbacon-2021-09-10.log](https://github.com/bakingbacon/bakinbacon/files/7145556/log-bakinbacon-2021-09-10.log)

**Comment by utdrmac** [comment]
You’re trying to delegate other accounts to the baker? That isn’t something BB handles. That’s completely on-chain and handled by the delegator’s client. What error are you getting? How are you delegating to this baker?

**Comment by reskue95** [comment]
I understand that bb does not handle this but at the moment i don't have endorsement rights and I am unable to add xtz to the balance.
I have sent the xtz to the address and it shows on the ledger but not on bb.
I have tried to delegate from ledger and other software wallets and none work and fail transaction.

is there anything else I can try has nothing I have tried is changing the balance or endorsement right.
so I am unable to bake at this time.

**Comment by utdrmac** [comment]
BB UI still shows 0 balance but tzkt (on granadanet) shows you do?

**Comment by reskue95** [comment]
Bb UI shows 8010 but tzkt only shows the test xtz I sent. So I haven't been able to bake yet



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by utdrmac** [comment]
Can you attach a screenshot of BB UI?

**Comment by reskue95** [comment]
![Screenshot 2021-09-11 at 14 48 32](https://user-images.githubusercontent.com/90354008/132950145-7e78e69c-e341-45a8-b31f-f12a04e18d17.png)

**Comment by utdrmac** [comment]
The screenshot shows your total baker balance at 8010XTZ, tzkt shows the same (https://granadanet.tzkt.io/tz1dTDGGnXepEsb7BTE7NEb6mViNRU1suzwX). I don't see any other transactions. You will not get baking rights for at least 3-5 more cycles. This is due to how the tezos chain works at a fundamental level. Everything looks correct; now it's the waiting game that all bakers must endure.

**Comment by reskue95** [comment]
brilliant thank you for the help.
