### ISSUE TITLE
Unable to access ledger: Cannot get ledger device: Ledger plugged in? Unlocked?

### ISSUE THREAD

**Issue by songproducer** [bakingbacon/bakinbacon#7]
1. Run ./bakinbacon-darwin-amd64 -debug -trace -webuiaddr 127.0.0.1 -webuiport 8082 -network granadanet
2. Go to http://127.0.0.1:8082/
3. Click Ledger Wallet button
4. Click Test Ledger button

Also seeing this error in the terminal:
error="Loading Delegate: No delegate key defined"

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.5.2 (20G95)
 - Browser Tried chrome, safari and brave
 - Version Ledger Live 2.32.2

**Comment by utdrmac** [comment]
Ledger doesn't interface through the UI. Browser has nothing to do with it. 

You're seeing that error cause nothing is configured yet. At what step do you get the "plugged in/unlocked?" message? Have you installed Tezos Baker app onto the ledger device?

**Comment by utdrmac** [comment]
@songproducer I'm on bigSur and can't get ledger to work either. Doesn't even work with latest Ledger Live 2.32.2. Not sure what changed in the past month with regards to MacOS security.

**Comment by songproducer** [comment]
> Ledger doesn't interface through the UI. Browser has nothing to do with it.

Yes, I’m aware. I’m already baking on another ledger, just trying to help test the setup process for new users.

> You're seeing that error cause nothing is configured yet. At what step do you get the "plugged in/unlocked?" message? Have you installed Tezos Baker app onto the ledger device?

Yes, I’ve installed the baker app but there’s no instructions on setting up a key as delegate.

**Comment by utdrmac** [comment]
>  just trying to help test the setup process for new users.

Thank you!

> Yes, I’ve installed the baker app but there’s no instructions on setting up a key as delegate.

The next step in the UI wizard will handle key selection, but you are not making it there because BB can't find your ledger. You're not running any debug/custom/non-genuine baking app on the ledger are you? Does LedgerLive find your device? Did you have to add LL to macos security preferences?

**Comment by songproducer** [comment]
I found the problem, was expecting it to work on Ledger Nano X. Just tried with Nano S and it finds that. Are there any plans to support baking on Nano X?

**Comment by utdrmac** [comment]
@songproducer I was under the (mistaken?) impression that the nano X does not support the tezos baking app. Am I wrong? I thought it only worked on the nano s.

**Comment by utdrmac** [comment]
Yea, official docs say baking is only for nano S. https://github.com/LedgerHQ/app-tezos
if you want to bake on NanoX, you need to tell Ledger to make the app work on it. BB interfaces with the app.

**Comment by songproducer** [comment]
It's available for the X and I was able to install it.

**Comment by songproducer** [comment]
I know it didn't used to be so I wonder if they are supporting soon?

**Comment by utdrmac** [comment]
I have a debug program for checking all of the ledger functionality. Can I send it to you and see if it recognizes the nano X? If so, guess I’ll have to get one and start testing it too.

**Comment by songproducer** [comment]
Sure.
